### ISSUE TITLE
Error when editing Tutorials Wiki page

### ISSUE THREAD

**Issue by ghost** [pyconca/2017-wiki#2]
I'm getting an error when I try to save a change to the Tutorials wiki page. (I'm just trying to add my name to the list for Stephen Astels's session.) The error page looks like it's probably GitHub's generic 500 internal server error page. I have been able to edit the Sprints page.

I have submitted an issue with GitHub support, but I thought I'd also open an issue here in case someone blocked me--my account was temporarily flagged by the spam filter shortly after I created it yesterday.

**Comment by myles** [comment]
I think that was just a temporary glitch with GitHub. It should work now.

If not I'll just manually add you to "Python can do that? Building
cross-platform graphical tools for Android and iOS with Kivy" - Stephen
Astels' tutorial.

**Comment by ghost** [comment]
I'm still getting the error, so if you could add me to the list for the "Python can do that?" tutorial, that would be wonderful.

Thanks!

**Comment by myles** [comment]
Done.
